name: love_calculator_holographic
version: 1.0.0+1
description: A stunning 3D holographic love calculator with mind-blowing visual effects

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  simple_animations: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/